analyzer:
  exclude:
    - build/**
    - lib/generated/oneops/**
    - lib/generated/mobistack/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    avoid_print: true
