// GENERATED by web-kit/packages/brand/scripts/build-tokens.mjs from tokens.json.
// Do not hand-edit. Change tokens.json and rebuild.
// This file is why web and Flutter can no longer drift: both are this one source.
// Contract: Infra/docs/UX-STANDARD.md

import 'dart:ui';

/// One resolved colour role set for a product in one theme mode.
class PxColors {
  const PxColors({
    required this.bg,
    required this.bgAccent,
    required this.surface,
    required this.surfaceRaised,
    required this.surfaceSunken,
    required this.surfaceHover,
    required this.surfaceActive,
    required this.surfaceSelected,
    required this.surfaceDisabled,
    required this.ink,
    required this.inkMuted,
    required this.inkFaint,
    required this.inkDisabled,
    required this.inkInverse,
    required this.border,
    required this.borderStrong,
    required this.borderAccent,
    required this.accent,
    required this.accentHover,
    required this.accentActive,
    required this.accentSelected,
    required this.accentDisabled,
    required this.accentInk,
    required this.accentSubtle,
    required this.accentSubtleInk,
    required this.accentSubtleBorder,
    required this.accent2,
    required this.accent2Hover,
    required this.accent2Ink,
    required this.accent2Subtle,
    required this.accent2SubtleInk,
    required this.accent2SubtleBorder,
    required this.success,
    required this.successInk,
    required this.successSubtle,
    required this.successSubtleInk,
    required this.successSubtleBorder,
    required this.warning,
    required this.warningInk,
    required this.warningSubtle,
    required this.warningSubtleInk,
    required this.warningSubtleBorder,
    required this.danger,
    required this.dangerHover,
    required this.dangerInk,
    required this.dangerSubtle,
    required this.dangerSubtleInk,
    required this.dangerSubtleBorder,
    required this.info,
    required this.infoInk,
    required this.infoSubtle,
    required this.infoSubtleInk,
    required this.infoSubtleBorder,
    required this.focus,
    required this.scrim,
  });

  final Color bg;
  final Color bgAccent;
  final Color surface;
  final Color surfaceRaised;
  final Color surfaceSunken;
  final Color surfaceHover;
  final Color surfaceActive;
  final Color surfaceSelected;
  final Color surfaceDisabled;
  final Color ink;
  final Color inkMuted;
  final Color inkFaint;
  final Color inkDisabled;
  final Color inkInverse;
  final Color border;
  final Color borderStrong;
  final Color borderAccent;
  final Color accent;
  final Color accentHover;
  final Color accentActive;
  final Color accentSelected;
  final Color accentDisabled;
  final Color accentInk;
  final Color accentSubtle;
  final Color accentSubtleInk;
  final Color accentSubtleBorder;
  final Color accent2;
  final Color accent2Hover;
  final Color accent2Ink;
  final Color accent2Subtle;
  final Color accent2SubtleInk;
  final Color accent2SubtleBorder;
  final Color success;
  final Color successInk;
  final Color successSubtle;
  final Color successSubtleInk;
  final Color successSubtleBorder;
  final Color warning;
  final Color warningInk;
  final Color warningSubtle;
  final Color warningSubtleInk;
  final Color warningSubtleBorder;
  final Color danger;
  final Color dangerHover;
  final Color dangerInk;
  final Color dangerSubtle;
  final Color dangerSubtleInk;
  final Color dangerSubtleBorder;
  final Color info;
  final Color infoInk;
  final Color infoSubtle;
  final Color infoSubtleInk;
  final Color infoSubtleBorder;
  final Color focus;
  final Color scrim;

  /// Used by [ThemeExtension.lerp] so a theme change animates instead of snapping.
  PxColors lerpTo(PxColors other, double t) => PxColors(
    bg: Color.lerp(bg, other.bg, t)!,
    bgAccent: Color.lerp(bgAccent, other.bgAccent, t)!,
    surface: Color.lerp(surface, other.surface, t)!,
    surfaceRaised: Color.lerp(surfaceRaised, other.surfaceRaised, t)!,
    surfaceSunken: Color.lerp(surfaceSunken, other.surfaceSunken, t)!,
    surfaceHover: Color.lerp(surfaceHover, other.surfaceHover, t)!,
    surfaceActive: Color.lerp(surfaceActive, other.surfaceActive, t)!,
    surfaceSelected: Color.lerp(surfaceSelected, other.surfaceSelected, t)!,
    surfaceDisabled: Color.lerp(surfaceDisabled, other.surfaceDisabled, t)!,
    ink: Color.lerp(ink, other.ink, t)!,
    inkMuted: Color.lerp(inkMuted, other.inkMuted, t)!,
    inkFaint: Color.lerp(inkFaint, other.inkFaint, t)!,
    inkDisabled: Color.lerp(inkDisabled, other.inkDisabled, t)!,
    inkInverse: Color.lerp(inkInverse, other.inkInverse, t)!,
    border: Color.lerp(border, other.border, t)!,
    borderStrong: Color.lerp(borderStrong, other.borderStrong, t)!,
    borderAccent: Color.lerp(borderAccent, other.borderAccent, t)!,
    accent: Color.lerp(accent, other.accent, t)!,
    accentHover: Color.lerp(accentHover, other.accentHover, t)!,
    accentActive: Color.lerp(accentActive, other.accentActive, t)!,
    accentSelected: Color.lerp(accentSelected, other.accentSelected, t)!,
    accentDisabled: Color.lerp(accentDisabled, other.accentDisabled, t)!,
    accentInk: Color.lerp(accentInk, other.accentInk, t)!,
    accentSubtle: Color.lerp(accentSubtle, other.accentSubtle, t)!,
    accentSubtleInk: Color.lerp(accentSubtleInk, other.accentSubtleInk, t)!,
    accentSubtleBorder: Color.lerp(accentSubtleBorder, other.accentSubtleBorder, t)!,
    accent2: Color.lerp(accent2, other.accent2, t)!,
    accent2Hover: Color.lerp(accent2Hover, other.accent2Hover, t)!,
    accent2Ink: Color.lerp(accent2Ink, other.accent2Ink, t)!,
    accent2Subtle: Color.lerp(accent2Subtle, other.accent2Subtle, t)!,
    accent2SubtleInk: Color.lerp(accent2SubtleInk, other.accent2SubtleInk, t)!,
    accent2SubtleBorder: Color.lerp(accent2SubtleBorder, other.accent2SubtleBorder, t)!,
    success: Color.lerp(success, other.success, t)!,
    successInk: Color.lerp(successInk, other.successInk, t)!,
    successSubtle: Color.lerp(successSubtle, other.successSubtle, t)!,
    successSubtleInk: Color.lerp(successSubtleInk, other.successSubtleInk, t)!,
    successSubtleBorder: Color.lerp(successSubtleBorder, other.successSubtleBorder, t)!,
    warning: Color.lerp(warning, other.warning, t)!,
    warningInk: Color.lerp(warningInk, other.warningInk, t)!,
    warningSubtle: Color.lerp(warningSubtle, other.warningSubtle, t)!,
    warningSubtleInk: Color.lerp(warningSubtleInk, other.warningSubtleInk, t)!,
    warningSubtleBorder: Color.lerp(warningSubtleBorder, other.warningSubtleBorder, t)!,
    danger: Color.lerp(danger, other.danger, t)!,
    dangerHover: Color.lerp(dangerHover, other.dangerHover, t)!,
    dangerInk: Color.lerp(dangerInk, other.dangerInk, t)!,
    dangerSubtle: Color.lerp(dangerSubtle, other.dangerSubtle, t)!,
    dangerSubtleInk: Color.lerp(dangerSubtleInk, other.dangerSubtleInk, t)!,
    dangerSubtleBorder: Color.lerp(dangerSubtleBorder, other.dangerSubtleBorder, t)!,
    info: Color.lerp(info, other.info, t)!,
    infoInk: Color.lerp(infoInk, other.infoInk, t)!,
    infoSubtle: Color.lerp(infoSubtle, other.infoSubtle, t)!,
    infoSubtleInk: Color.lerp(infoSubtleInk, other.infoSubtleInk, t)!,
    infoSubtleBorder: Color.lerp(infoSubtleBorder, other.infoSubtleBorder, t)!,
    focus: Color.lerp(focus, other.focus, t)!,
    scrim: Color.lerp(scrim, other.scrim, t)!,
  );
}

/// Spacing, radius and type scales. Shared by every product, never overridden.
class PxSpace {
  static const double s0 = 0;
  static const double s1 = 4;
  static const double s2 = 8;
  static const double s3 = 12;
  static const double s4 = 16;
  static const double s5 = 20;
  static const double s6 = 24;
  static const double s8 = 32;
  static const double s10 = 40;
  static const double s12 = 48;
  static const double s16 = 64;
  static const double s20 = 80;
  static const double s24 = 96;
  static const double spx = 1;
  static const double s0_5 = 2;
  static const double s1_5 = 6;
}

class PxRadius {
  static const double sm = 6;
  static const double md = 10;
  static const double lg = 14;
  static const double xl = 20;
  static const double full = 9999;
}

class PxDuration {
  static const Duration instant = Duration(milliseconds: 0);
  static const Duration fast = Duration(milliseconds: 120);
  static const Duration normal = Duration(milliseconds: 180);
  static const Duration slow = Duration(milliseconds: 280);
}

class PxType {
  static const double displaySize = 48;
  static const double displayHeight = 1.05;
  static const int displayWeight = 700;
  static const double displayTracking = -0.96;
  static const double titleLgSize = 28;
  static const double titleLgHeight = 1.2;
  static const int titleLgWeight = 700;
  static const double titleLgTracking = -0.28;
  static const double titleMdSize = 20;
  static const double titleMdHeight = 1.3;
  static const int titleMdWeight = 600;
  static const double titleMdTracking = -0.1;
  static const double titleSmSize = 16;
  static const double titleSmHeight = 1.4;
  static const int titleSmWeight = 600;
  static const double titleSmTracking = 0;
  static const double bodyLgSize = 17;
  static const double bodyLgHeight = 1.6;
  static const int bodyLgWeight = 400;
  static const double bodyLgTracking = 0;
  static const double bodyMdSize = 15;
  static const double bodyMdHeight = 1.55;
  static const int bodyMdWeight = 400;
  static const double bodyMdTracking = 0;
  static const double bodySmSize = 14;
  static const double bodySmHeight = 1.5;
  static const int bodySmWeight = 400;
  static const double bodySmTracking = 0;
  static const double labelSize = 13;
  static const double labelHeight = 1.4;
  static const int labelWeight = 600;
  static const double labelTracking = 0.13;
  static const double captionSize = 12;
  static const double captionHeight = 1.4;
  static const int captionWeight = 400;
  static const double captionTracking = 0.12;
  static const double overlineSize = 11;
  static const double overlineHeight = 1.3;
  static const int overlineWeight = 600;
  static const double overlineTracking = 1.1;
  static const double monoSize = 14;
  static const double monoHeight = 1.5;
  static const int monoWeight = 400;
  static const double monoTracking = 0;
}

/// Prabhix Technologies — light
const PxColors pxTechnologiesLight = PxColors(
  bg: Color(0xFFEEF2F7),
  bgAccent: Color(0xFFECFEFF),
  surface: Color(0xFFF6F8FB),
  surfaceRaised: Color(0xFFFFFFFF),
  surfaceSunken: Color(0xFFDFE6EF),
  surfaceHover: Color(0xFFEEF2F7),
  surfaceActive: Color(0xFFDFE6EF),
  surfaceSelected: Color(0xFFECFEFF),
  surfaceDisabled: Color(0xFFDFE6EF),
  ink: Color(0xFF0C1524),
  inkMuted: Color(0xFF56687E),
  inkFaint: Color(0xFF71859D),
  inkDisabled: Color(0xFF9AABC0),
  inkInverse: Color(0xFFFFFFFF),
  border: Color(0xFFC8D4E1),
  borderStrong: Color(0xFF71859D),
  borderAccent: Color(0xFF0891B2),
  accent: Color(0xFF0E7490),
  accentHover: Color(0xFF155E75),
  accentActive: Color(0xFF164E63),
  accentSelected: Color(0xFFCFFAFE),
  accentDisabled: Color(0xFFC8D4E1),
  accentInk: Color(0xFFFFFFFF),
  accentSubtle: Color(0xFFECFEFF),
  accentSubtleInk: Color(0xFF155E75),
  accentSubtleBorder: Color(0xFFA5F3FC),
  accent2: Color(0xFF4338CA),
  accent2Hover: Color(0xFF3730A3),
  accent2Ink: Color(0xFFFFFFFF),
  accent2Subtle: Color(0xFFEEF2FF),
  accent2SubtleInk: Color(0xFF3730A3),
  accent2SubtleBorder: Color(0xFFC7D2FE),
  success: Color(0xFF027A48),
  successInk: Color(0xFFFFFFFF),
  successSubtle: Color(0xFFECFDF3),
  successSubtleInk: Color(0xFF05603A),
  successSubtleBorder: Color(0xFFA6F4C5),
  warning: Color(0xFFA16207),
  warningInk: Color(0xFFFFFFFF),
  warningSubtle: Color(0xFFFEFCE8),
  warningSubtleInk: Color(0xFF854D0E),
  warningSubtleBorder: Color(0xFFFEF08A),
  danger: Color(0xFFB42318),
  dangerHover: Color(0xFF912018),
  dangerInk: Color(0xFFFFFFFF),
  dangerSubtle: Color(0xFFFEF3F2),
  dangerSubtleInk: Color(0xFF912018),
  dangerSubtleBorder: Color(0xFFFECDCA),
  info: Color(0xFF1D4ED8),
  infoInk: Color(0xFFFFFFFF),
  infoSubtle: Color(0xFFEFF6FF),
  infoSubtleInk: Color(0xFF1E40AF),
  infoSubtleBorder: Color(0xFFBFDBFE),
  focus: Color(0xFF0E7490),
  scrim: Color(0xFF0C1524),
);

/// Prabhix Technologies — dark
const PxColors pxTechnologiesDark = PxColors(
  bg: Color(0xFF0C1524),
  bgAccent: Color(0xFF083344),
  surface: Color(0xFF1A2532),
  surfaceRaised: Color(0xFF2C3A49),
  surfaceSunken: Color(0xFF0C1524),
  surfaceHover: Color(0xFF2C3A49),
  surfaceActive: Color(0xFF435365),
  surfaceSelected: Color(0xFF083344),
  surfaceDisabled: Color(0xFF2C3A49),
  ink: Color(0xFFF6F8FB),
  inkMuted: Color(0xFF9AABC0),
  inkFaint: Color(0xFF71859D),
  inkDisabled: Color(0xFF56687E),
  inkInverse: Color(0xFF0C1524),
  border: Color(0xFF2C3A49),
  borderStrong: Color(0xFF71859D),
  borderAccent: Color(0xFF22D3EE),
  accent: Color(0xFF22D3EE),
  accentHover: Color(0xFF67E8F9),
  accentActive: Color(0xFFA5F3FC),
  accentSelected: Color(0xFF164E63),
  accentDisabled: Color(0xFF435365),
  accentInk: Color(0xFF083344),
  accentSubtle: Color(0xFF083344),
  accentSubtleInk: Color(0xFF67E8F9),
  accentSubtleBorder: Color(0xFF164E63),
  accent2: Color(0xFF818CF8),
  accent2Hover: Color(0xFFA5B4FC),
  accent2Ink: Color(0xFF1E1B4B),
  accent2Subtle: Color(0xFF1E1B4B),
  accent2SubtleInk: Color(0xFFA5B4FC),
  accent2SubtleBorder: Color(0xFF312E81),
  success: Color(0xFF32D583),
  successInk: Color(0xFF053321),
  successSubtle: Color(0xFF053321),
  successSubtleInk: Color(0xFF6CE9A6),
  successSubtleBorder: Color(0xFF054F31),
  warning: Color(0xFFFACC15),
  warningInk: Color(0xFF422006),
  warningSubtle: Color(0xFF422006),
  warningSubtleInk: Color(0xFFFDE047),
  warningSubtleBorder: Color(0xFF713F12),
  danger: Color(0xFFF97066),
  dangerHover: Color(0xFFFDA29B),
  dangerInk: Color(0xFF55160C),
  dangerSubtle: Color(0xFF55160C),
  dangerSubtleInk: Color(0xFFFDA29B),
  dangerSubtleBorder: Color(0xFF7A271A),
  info: Color(0xFF60A5FA),
  infoInk: Color(0xFF172554),
  infoSubtle: Color(0xFF172554),
  infoSubtleInk: Color(0xFF93C5FD),
  infoSubtleBorder: Color(0xFF1E3A8A),
  focus: Color(0xFF67E8F9),
  scrim: Color(0xFF000000),
);

/// OneOps — light
const PxColors pxOneopsLight = PxColors(
  bg: Color(0xFFEEF2F7),
  bgAccent: Color(0xFFEEF2FF),
  surface: Color(0xFFF6F8FB),
  surfaceRaised: Color(0xFFFFFFFF),
  surfaceSunken: Color(0xFFDFE6EF),
  surfaceHover: Color(0xFFEEF2F7),
  surfaceActive: Color(0xFFDFE6EF),
  surfaceSelected: Color(0xFFEEF2FF),
  surfaceDisabled: Color(0xFFDFE6EF),
  ink: Color(0xFF0C1524),
  inkMuted: Color(0xFF56687E),
  inkFaint: Color(0xFF71859D),
  inkDisabled: Color(0xFF9AABC0),
  inkInverse: Color(0xFFFFFFFF),
  border: Color(0xFFC8D4E1),
  borderStrong: Color(0xFF71859D),
  borderAccent: Color(0xFF4F46E5),
  accent: Color(0xFF4338CA),
  accentHover: Color(0xFF3730A3),
  accentActive: Color(0xFF312E81),
  accentSelected: Color(0xFFE0E7FF),
  accentDisabled: Color(0xFFC8D4E1),
  accentInk: Color(0xFFFFFFFF),
  accentSubtle: Color(0xFFEEF2FF),
  accentSubtleInk: Color(0xFF3730A3),
  accentSubtleBorder: Color(0xFFC7D2FE),
  accent2: Color(0xFFA21CAF),
  accent2Hover: Color(0xFF86198F),
  accent2Ink: Color(0xFFFFFFFF),
  accent2Subtle: Color(0xFFFDF4FF),
  accent2SubtleInk: Color(0xFF86198F),
  accent2SubtleBorder: Color(0xFFF5D0FE),
  success: Color(0xFF027A48),
  successInk: Color(0xFFFFFFFF),
  successSubtle: Color(0xFFECFDF3),
  successSubtleInk: Color(0xFF05603A),
  successSubtleBorder: Color(0xFFA6F4C5),
  warning: Color(0xFFA16207),
  warningInk: Color(0xFFFFFFFF),
  warningSubtle: Color(0xFFFEFCE8),
  warningSubtleInk: Color(0xFF854D0E),
  warningSubtleBorder: Color(0xFFFEF08A),
  danger: Color(0xFFB42318),
  dangerHover: Color(0xFF912018),
  dangerInk: Color(0xFFFFFFFF),
  dangerSubtle: Color(0xFFFEF3F2),
  dangerSubtleInk: Color(0xFF912018),
  dangerSubtleBorder: Color(0xFFFECDCA),
  info: Color(0xFF1D4ED8),
  infoInk: Color(0xFFFFFFFF),
  infoSubtle: Color(0xFFEFF6FF),
  infoSubtleInk: Color(0xFF1E40AF),
  infoSubtleBorder: Color(0xFFBFDBFE),
  focus: Color(0xFF4338CA),
  scrim: Color(0xFF0C1524),
);

/// OneOps — dark
const PxColors pxOneopsDark = PxColors(
  bg: Color(0xFF0C1524),
  bgAccent: Color(0xFF1E1B4B),
  surface: Color(0xFF1A2532),
  surfaceRaised: Color(0xFF2C3A49),
  surfaceSunken: Color(0xFF0C1524),
  surfaceHover: Color(0xFF2C3A49),
  surfaceActive: Color(0xFF435365),
  surfaceSelected: Color(0xFF1E1B4B),
  surfaceDisabled: Color(0xFF2C3A49),
  ink: Color(0xFFF6F8FB),
  inkMuted: Color(0xFF9AABC0),
  inkFaint: Color(0xFF71859D),
  inkDisabled: Color(0xFF56687E),
  inkInverse: Color(0xFF0C1524),
  border: Color(0xFF2C3A49),
  borderStrong: Color(0xFF71859D),
  borderAccent: Color(0xFF818CF8),
  accent: Color(0xFF818CF8),
  accentHover: Color(0xFFA5B4FC),
  accentActive: Color(0xFFC7D2FE),
  accentSelected: Color(0xFF312E81),
  accentDisabled: Color(0xFF435365),
  accentInk: Color(0xFF1E1B4B),
  accentSubtle: Color(0xFF1E1B4B),
  accentSubtleInk: Color(0xFFA5B4FC),
  accentSubtleBorder: Color(0xFF312E81),
  accent2: Color(0xFFE879F9),
  accent2Hover: Color(0xFFF0ABFC),
  accent2Ink: Color(0xFF4A044E),
  accent2Subtle: Color(0xFF4A044E),
  accent2SubtleInk: Color(0xFFF0ABFC),
  accent2SubtleBorder: Color(0xFF701A75),
  success: Color(0xFF32D583),
  successInk: Color(0xFF053321),
  successSubtle: Color(0xFF053321),
  successSubtleInk: Color(0xFF6CE9A6),
  successSubtleBorder: Color(0xFF054F31),
  warning: Color(0xFFFACC15),
  warningInk: Color(0xFF422006),
  warningSubtle: Color(0xFF422006),
  warningSubtleInk: Color(0xFFFDE047),
  warningSubtleBorder: Color(0xFF713F12),
  danger: Color(0xFFF97066),
  dangerHover: Color(0xFFFDA29B),
  dangerInk: Color(0xFF55160C),
  dangerSubtle: Color(0xFF55160C),
  dangerSubtleInk: Color(0xFFFDA29B),
  dangerSubtleBorder: Color(0xFF7A271A),
  info: Color(0xFF60A5FA),
  infoInk: Color(0xFF172554),
  infoSubtle: Color(0xFF172554),
  infoSubtleInk: Color(0xFF93C5FD),
  infoSubtleBorder: Color(0xFF1E3A8A),
  focus: Color(0xFFA5B4FC),
  scrim: Color(0xFF000000),
);

/// Admin console — light
const PxColors pxAdminLight = PxColors(
  bg: Color(0xFFEEF2F7),
  bgAccent: Color(0xFFF5F3FF),
  surface: Color(0xFFF6F8FB),
  surfaceRaised: Color(0xFFFFFFFF),
  surfaceSunken: Color(0xFFDFE6EF),
  surfaceHover: Color(0xFFEEF2F7),
  surfaceActive: Color(0xFFDFE6EF),
  surfaceSelected: Color(0xFFF5F3FF),
  surfaceDisabled: Color(0xFFDFE6EF),
  ink: Color(0xFF0C1524),
  inkMuted: Color(0xFF56687E),
  inkFaint: Color(0xFF71859D),
  inkDisabled: Color(0xFF9AABC0),
  inkInverse: Color(0xFFFFFFFF),
  border: Color(0xFFC8D4E1),
  borderStrong: Color(0xFF71859D),
  borderAccent: Color(0xFF7C3AED),
  accent: Color(0xFF6D28D9),
  accentHover: Color(0xFF5B21B6),
  accentActive: Color(0xFF4C1D95),
  accentSelected: Color(0xFFEDE9FE),
  accentDisabled: Color(0xFFC8D4E1),
  accentInk: Color(0xFFFFFFFF),
  accentSubtle: Color(0xFFF5F3FF),
  accentSubtleInk: Color(0xFF5B21B6),
  accentSubtleBorder: Color(0xFFDDD6FE),
  accent2: Color(0xFF0E7490),
  accent2Hover: Color(0xFF155E75),
  accent2Ink: Color(0xFFFFFFFF),
  accent2Subtle: Color(0xFFECFEFF),
  accent2SubtleInk: Color(0xFF155E75),
  accent2SubtleBorder: Color(0xFFA5F3FC),
  success: Color(0xFF027A48),
  successInk: Color(0xFFFFFFFF),
  successSubtle: Color(0xFFECFDF3),
  successSubtleInk: Color(0xFF05603A),
  successSubtleBorder: Color(0xFFA6F4C5),
  warning: Color(0xFFA16207),
  warningInk: Color(0xFFFFFFFF),
  warningSubtle: Color(0xFFFEFCE8),
  warningSubtleInk: Color(0xFF854D0E),
  warningSubtleBorder: Color(0xFFFEF08A),
  danger: Color(0xFFB42318),
  dangerHover: Color(0xFF912018),
  dangerInk: Color(0xFFFFFFFF),
  dangerSubtle: Color(0xFFFEF3F2),
  dangerSubtleInk: Color(0xFF912018),
  dangerSubtleBorder: Color(0xFFFECDCA),
  info: Color(0xFF1D4ED8),
  infoInk: Color(0xFFFFFFFF),
  infoSubtle: Color(0xFFEFF6FF),
  infoSubtleInk: Color(0xFF1E40AF),
  infoSubtleBorder: Color(0xFFBFDBFE),
  focus: Color(0xFF6D28D9),
  scrim: Color(0xFF0C1524),
);

/// Admin console — dark
const PxColors pxAdminDark = PxColors(
  bg: Color(0xFF0C1524),
  bgAccent: Color(0xFF2E1065),
  surface: Color(0xFF1A2532),
  surfaceRaised: Color(0xFF2C3A49),
  surfaceSunken: Color(0xFF0C1524),
  surfaceHover: Color(0xFF2C3A49),
  surfaceActive: Color(0xFF435365),
  surfaceSelected: Color(0xFF2E1065),
  surfaceDisabled: Color(0xFF2C3A49),
  ink: Color(0xFFF6F8FB),
  inkMuted: Color(0xFF9AABC0),
  inkFaint: Color(0xFF71859D),
  inkDisabled: Color(0xFF56687E),
  inkInverse: Color(0xFF0C1524),
  border: Color(0xFF2C3A49),
  borderStrong: Color(0xFF71859D),
  borderAccent: Color(0xFFA78BFA),
  accent: Color(0xFFA78BFA),
  accentHover: Color(0xFFC4B5FD),
  accentActive: Color(0xFFDDD6FE),
  accentSelected: Color(0xFF4C1D95),
  accentDisabled: Color(0xFF435365),
  accentInk: Color(0xFF2E1065),
  accentSubtle: Color(0xFF2E1065),
  accentSubtleInk: Color(0xFFC4B5FD),
  accentSubtleBorder: Color(0xFF4C1D95),
  accent2: Color(0xFF22D3EE),
  accent2Hover: Color(0xFF67E8F9),
  accent2Ink: Color(0xFF083344),
  accent2Subtle: Color(0xFF083344),
  accent2SubtleInk: Color(0xFF67E8F9),
  accent2SubtleBorder: Color(0xFF164E63),
  success: Color(0xFF32D583),
  successInk: Color(0xFF053321),
  successSubtle: Color(0xFF053321),
  successSubtleInk: Color(0xFF6CE9A6),
  successSubtleBorder: Color(0xFF054F31),
  warning: Color(0xFFFACC15),
  warningInk: Color(0xFF422006),
  warningSubtle: Color(0xFF422006),
  warningSubtleInk: Color(0xFFFDE047),
  warningSubtleBorder: Color(0xFF713F12),
  danger: Color(0xFFF97066),
  dangerHover: Color(0xFFFDA29B),
  dangerInk: Color(0xFF55160C),
  dangerSubtle: Color(0xFF55160C),
  dangerSubtleInk: Color(0xFFFDA29B),
  dangerSubtleBorder: Color(0xFF7A271A),
  info: Color(0xFF60A5FA),
  infoInk: Color(0xFF172554),
  infoSubtle: Color(0xFF172554),
  infoSubtleInk: Color(0xFF93C5FD),
  infoSubtleBorder: Color(0xFF1E3A8A),
  focus: Color(0xFFC4B5FD),
  scrim: Color(0xFF000000),
);

/// MobiStack — light
const PxColors pxMobistackLight = PxColors(
  bg: Color(0xFFF4F1EA),
  bgAccent: Color(0xFFFFFBEB),
  surface: Color(0xFFFAF8F4),
  surfaceRaised: Color(0xFFFFFFFF),
  surfaceSunken: Color(0xFFE9E3D7),
  surfaceHover: Color(0xFFF4F1EA),
  surfaceActive: Color(0xFFE9E3D7),
  surfaceSelected: Color(0xFFFFFBEB),
  surfaceDisabled: Color(0xFFE9E3D7),
  ink: Color(0xFF12100E),
  inkMuted: Color(0xFF6A6358),
  inkFaint: Color(0xFF8D8273),
  inkDisabled: Color(0xFFB3A993),
  inkInverse: Color(0xFFFFFFFF),
  border: Color(0xFFD8D0BF),
  borderStrong: Color(0xFF8D8273),
  borderAccent: Color(0xFFD97706),
  accent: Color(0xFFB45309),
  accentHover: Color(0xFF92400E),
  accentActive: Color(0xFF78350F),
  accentSelected: Color(0xFFFEF3C7),
  accentDisabled: Color(0xFFD8D0BF),
  accentInk: Color(0xFFFFFFFF),
  accentSubtle: Color(0xFFFFFBEB),
  accentSubtleInk: Color(0xFF92400E),
  accentSubtleBorder: Color(0xFFFDE68A),
  accent2: Color(0xFF0F766E),
  accent2Hover: Color(0xFF115E59),
  accent2Ink: Color(0xFFFFFFFF),
  accent2Subtle: Color(0xFFF0FDFA),
  accent2SubtleInk: Color(0xFF115E59),
  accent2SubtleBorder: Color(0xFF99F6E4),
  success: Color(0xFF027A48),
  successInk: Color(0xFFFFFFFF),
  successSubtle: Color(0xFFECFDF3),
  successSubtleInk: Color(0xFF05603A),
  successSubtleBorder: Color(0xFFA6F4C5),
  warning: Color(0xFFA16207),
  warningInk: Color(0xFFFFFFFF),
  warningSubtle: Color(0xFFFEFCE8),
  warningSubtleInk: Color(0xFF854D0E),
  warningSubtleBorder: Color(0xFFFEF08A),
  danger: Color(0xFFB42318),
  dangerHover: Color(0xFF912018),
  dangerInk: Color(0xFFFFFFFF),
  dangerSubtle: Color(0xFFFEF3F2),
  dangerSubtleInk: Color(0xFF912018),
  dangerSubtleBorder: Color(0xFFFECDCA),
  info: Color(0xFF1D4ED8),
  infoInk: Color(0xFFFFFFFF),
  infoSubtle: Color(0xFFEFF6FF),
  infoSubtleInk: Color(0xFF1E40AF),
  infoSubtleBorder: Color(0xFFBFDBFE),
  focus: Color(0xFFB45309),
  scrim: Color(0xFF12100E),
);

/// MobiStack — dark
const PxColors pxMobistackDark = PxColors(
  bg: Color(0xFF12100E),
  bgAccent: Color(0xFF451A03),
  surface: Color(0xFF221F1A),
  surfaceRaised: Color(0xFF35312C),
  surfaceSunken: Color(0xFF12100E),
  surfaceHover: Color(0xFF35312C),
  surfaceActive: Color(0xFF514B43),
  surfaceSelected: Color(0xFF451A03),
  surfaceDisabled: Color(0xFF35312C),
  ink: Color(0xFFFAF8F4),
  inkMuted: Color(0xFFB3A993),
  inkFaint: Color(0xFF8D8273),
  inkDisabled: Color(0xFF6A6358),
  inkInverse: Color(0xFF12100E),
  border: Color(0xFF35312C),
  borderStrong: Color(0xFF8D8273),
  borderAccent: Color(0xFFFBBF24),
  accent: Color(0xFFFBBF24),
  accentHover: Color(0xFFFCD34D),
  accentActive: Color(0xFFFDE68A),
  accentSelected: Color(0xFF78350F),
  accentDisabled: Color(0xFF514B43),
  accentInk: Color(0xFF451A03),
  accentSubtle: Color(0xFF451A03),
  accentSubtleInk: Color(0xFFFCD34D),
  accentSubtleBorder: Color(0xFF78350F),
  accent2: Color(0xFF2DD4BF),
  accent2Hover: Color(0xFF5EEAD4),
  accent2Ink: Color(0xFF042F2E),
  accent2Subtle: Color(0xFF042F2E),
  accent2SubtleInk: Color(0xFF5EEAD4),
  accent2SubtleBorder: Color(0xFF134E4A),
  success: Color(0xFF32D583),
  successInk: Color(0xFF053321),
  successSubtle: Color(0xFF053321),
  successSubtleInk: Color(0xFF6CE9A6),
  successSubtleBorder: Color(0xFF054F31),
  warning: Color(0xFFFACC15),
  warningInk: Color(0xFF422006),
  warningSubtle: Color(0xFF422006),
  warningSubtleInk: Color(0xFFFDE047),
  warningSubtleBorder: Color(0xFF713F12),
  danger: Color(0xFFF97066),
  dangerHover: Color(0xFFFDA29B),
  dangerInk: Color(0xFF55160C),
  dangerSubtle: Color(0xFF55160C),
  dangerSubtleInk: Color(0xFFFDA29B),
  dangerSubtleBorder: Color(0xFF7A271A),
  info: Color(0xFF60A5FA),
  infoInk: Color(0xFF172554),
  infoSubtle: Color(0xFF172554),
  infoSubtleInk: Color(0xFF93C5FD),
  infoSubtleBorder: Color(0xFF1E3A8A),
  focus: Color(0xFFFCD34D),
  scrim: Color(0xFF000000),
);

/// Mailroom — light
const PxColors pxMailroomLight = PxColors(
  bg: Color(0xFFF4F1EA),
  bgAccent: Color(0xFFFBF4F1),
  surface: Color(0xFFFAF8F4),
  surfaceRaised: Color(0xFFFFFFFF),
  surfaceSunken: Color(0xFFE9E3D7),
  surfaceHover: Color(0xFFF4F1EA),
  surfaceActive: Color(0xFFE9E3D7),
  surfaceSelected: Color(0xFFFBF4F1),
  surfaceDisabled: Color(0xFFE9E3D7),
  ink: Color(0xFF12100E),
  inkMuted: Color(0xFF6A6358),
  inkFaint: Color(0xFF8D8273),
  inkDisabled: Color(0xFFB3A993),
  inkInverse: Color(0xFFFFFFFF),
  border: Color(0xFFD8D0BF),
  borderStrong: Color(0xFF8D8273),
  borderAccent: Color(0xFF9A4834),
  accent: Color(0xFF8C3B2A),
  accentHover: Color(0xFF713024),
  accentActive: Color(0xFF5C2A20),
  accentSelected: Color(0xFFF6E6DF),
  accentDisabled: Color(0xFFD8D0BF),
  accentInk: Color(0xFFFFFFFF),
  accentSubtle: Color(0xFFFBF4F1),
  accentSubtleInk: Color(0xFF713024),
  accentSubtleBorder: Color(0xFFECCCBE),
  accent2: Color(0xFF0F766E),
  accent2Hover: Color(0xFF115E59),
  accent2Ink: Color(0xFFFFFFFF),
  accent2Subtle: Color(0xFFF0FDFA),
  accent2SubtleInk: Color(0xFF115E59),
  accent2SubtleBorder: Color(0xFF99F6E4),
  success: Color(0xFF027A48),
  successInk: Color(0xFFFFFFFF),
  successSubtle: Color(0xFFECFDF3),
  successSubtleInk: Color(0xFF05603A),
  successSubtleBorder: Color(0xFFA6F4C5),
  warning: Color(0xFFA16207),
  warningInk: Color(0xFFFFFFFF),
  warningSubtle: Color(0xFFFEFCE8),
  warningSubtleInk: Color(0xFF854D0E),
  warningSubtleBorder: Color(0xFFFEF08A),
  danger: Color(0xFFB42318),
  dangerHover: Color(0xFF912018),
  dangerInk: Color(0xFFFFFFFF),
  dangerSubtle: Color(0xFFFEF3F2),
  dangerSubtleInk: Color(0xFF912018),
  dangerSubtleBorder: Color(0xFFFECDCA),
  info: Color(0xFF1D4ED8),
  infoInk: Color(0xFFFFFFFF),
  infoSubtle: Color(0xFFEFF6FF),
  infoSubtleInk: Color(0xFF1E40AF),
  infoSubtleBorder: Color(0xFFBFDBFE),
  focus: Color(0xFF8C3B2A),
  scrim: Color(0xFF12100E),
);

/// Mailroom — dark
const PxColors pxMailroomDark = PxColors(
  bg: Color(0xFF12100E),
  bgAccent: Color(0xFF331512),
  surface: Color(0xFF221F1A),
  surfaceRaised: Color(0xFF35312C),
  surfaceSunken: Color(0xFF12100E),
  surfaceHover: Color(0xFF35312C),
  surfaceActive: Color(0xFF514B43),
  surfaceSelected: Color(0xFF331512),
  surfaceDisabled: Color(0xFF35312C),
  ink: Color(0xFFFAF8F4),
  inkMuted: Color(0xFFB3A993),
  inkFaint: Color(0xFF8D8273),
  inkDisabled: Color(0xFF6A6358),
  inkInverse: Color(0xFF12100E),
  border: Color(0xFF35312C),
  borderStrong: Color(0xFF8D8273),
  borderAccent: Color(0xFFC17A62),
  accent: Color(0xFFC17A62),
  accentHover: Color(0xFFDDA894),
  accentActive: Color(0xFFECCCBE),
  accentSelected: Color(0xFF5C2A20),
  accentDisabled: Color(0xFF514B43),
  accentInk: Color(0xFF331512),
  accentSubtle: Color(0xFF331512),
  accentSubtleInk: Color(0xFFDDA894),
  accentSubtleBorder: Color(0xFF5C2A20),
  accent2: Color(0xFF2DD4BF),
  accent2Hover: Color(0xFF5EEAD4),
  accent2Ink: Color(0xFF042F2E),
  accent2Subtle: Color(0xFF042F2E),
  accent2SubtleInk: Color(0xFF5EEAD4),
  accent2SubtleBorder: Color(0xFF134E4A),
  success: Color(0xFF32D583),
  successInk: Color(0xFF053321),
  successSubtle: Color(0xFF053321),
  successSubtleInk: Color(0xFF6CE9A6),
  successSubtleBorder: Color(0xFF054F31),
  warning: Color(0xFFFACC15),
  warningInk: Color(0xFF422006),
  warningSubtle: Color(0xFF422006),
  warningSubtleInk: Color(0xFFFDE047),
  warningSubtleBorder: Color(0xFF713F12),
  danger: Color(0xFFF97066),
  dangerHover: Color(0xFFFDA29B),
  dangerInk: Color(0xFF55160C),
  dangerSubtle: Color(0xFF55160C),
  dangerSubtleInk: Color(0xFFFDA29B),
  dangerSubtleBorder: Color(0xFF7A271A),
  info: Color(0xFF60A5FA),
  infoInk: Color(0xFF172554),
  infoSubtle: Color(0xFF172554),
  infoSubtleInk: Color(0xFF93C5FD),
  infoSubtleBorder: Color(0xFF1E3A8A),
  focus: Color(0xFFDDA894),
  scrim: Color(0xFF000000),
);

/// Every product theme, by the same key used by [data-brand] on the web.
const Map<String, ({PxColors light, PxColors dark})> pxThemes = {
  'technologies': (light: pxTechnologiesLight, dark: pxTechnologiesDark),
  'oneops': (light: pxOneopsLight, dark: pxOneopsDark),
  'admin': (light: pxAdminLight, dark: pxAdminDark),
  'mobistack': (light: pxMobistackLight, dark: pxMobistackDark),
  'mailroom': (light: pxMailroomLight, dark: pxMailroomDark),
};

/// Categorical series colours for charts and generated avatars.
const List<Color> pxCategoricalLight = [Color(0xFF4338CA), Color(0xFF0891B2), Color(0xFFB45309), Color(0xFF039855), Color(0xFF9333EA), Color(0xFF8C3B2A), Color(0xFF0D9488), Color(0xFF4D7C0F), Color(0xFF2563EB), Color(0xFFDB2777)];
const List<Color> pxCategoricalDark = [Color(0xFFA5B4FC), Color(0xFF22D3EE), Color(0xFFFBBF24), Color(0xFF32D583), Color(0xFFC084FC), Color(0xFFDDA894), Color(0xFF2DD4BF), Color(0xFFA3E635), Color(0xFF60A5FA), Color(0xFFF472B6)];

/// One tinted label swatch: a fill, ink that clears 4.5:1 on that fill, and a hairline.
class PxTag {
  const PxTag(this.name, this.bg, this.ink, this.border);
  final String name;
  final Color bg;
  final Color ink;
  final Color border;
}

/// The tinted label palette, in the same order as the web so a category that is
/// violet in a browser is violet in the app.
const List<PxTag> pxTagLight = [
  PxTag('neutral', Color(0xFFEEF2F7), Color(0xFF2C3A49), Color(0xFFDFE6EF)),
  PxTag('red', Color(0xFFFEE4E2), Color(0xFF912018), Color(0xFFFECDCA)),
  PxTag('rose', Color(0xFFFFE4E6), Color(0xFF9F1239), Color(0xFFFECDD3)),
  PxTag('pink', Color(0xFFFCE7F3), Color(0xFF9D174D), Color(0xFFFBCFE8)),
  PxTag('fuchsia', Color(0xFFFAE8FF), Color(0xFF86198F), Color(0xFFF5D0FE)),
  PxTag('violet', Color(0xFFEDE9FE), Color(0xFF5B21B6), Color(0xFFDDD6FE)),
  PxTag('indigo', Color(0xFFE0E7FF), Color(0xFF3730A3), Color(0xFFC7D2FE)),
  PxTag('blue', Color(0xFFDBEAFE), Color(0xFF1E40AF), Color(0xFFBFDBFE)),
  PxTag('cyan', Color(0xFFCFFAFE), Color(0xFF155E75), Color(0xFFA5F3FC)),
  PxTag('teal', Color(0xFFCCFBF1), Color(0xFF115E59), Color(0xFF99F6E4)),
  PxTag('green', Color(0xFFD1FADF), Color(0xFF05603A), Color(0xFFA6F4C5)),
  PxTag('lime', Color(0xFFECFCCB), Color(0xFF3F6212), Color(0xFFD9F99D)),
  PxTag('yellow', Color(0xFFFEF9C3), Color(0xFF854D0E), Color(0xFFFEF08A)),
  PxTag('ochre', Color(0xFFFEF3C7), Color(0xFF92400E), Color(0xFFFDE68A)),
  PxTag('clay', Color(0xFFF6E6DF), Color(0xFF713024), Color(0xFFECCCBE)),
];

const List<PxTag> pxTagDark = [
  PxTag('neutral', Color(0xFF0C1524), Color(0xFFC8D4E1), Color(0xFF1A2532)),
  PxTag('red', Color(0xFF55160C), Color(0xFFFDA29B), Color(0xFF7A271A)),
  PxTag('rose', Color(0xFF4C0519), Color(0xFFFDA4AF), Color(0xFF881337)),
  PxTag('pink', Color(0xFF500724), Color(0xFFF9A8D4), Color(0xFF831843)),
  PxTag('fuchsia', Color(0xFF4A044E), Color(0xFFF0ABFC), Color(0xFF701A75)),
  PxTag('violet', Color(0xFF2E1065), Color(0xFFC4B5FD), Color(0xFF4C1D95)),
  PxTag('indigo', Color(0xFF1E1B4B), Color(0xFFA5B4FC), Color(0xFF312E81)),
  PxTag('blue', Color(0xFF172554), Color(0xFF93C5FD), Color(0xFF1E3A8A)),
  PxTag('cyan', Color(0xFF083344), Color(0xFF67E8F9), Color(0xFF164E63)),
  PxTag('teal', Color(0xFF042F2E), Color(0xFF5EEAD4), Color(0xFF134E4A)),
  PxTag('green', Color(0xFF053321), Color(0xFF6CE9A6), Color(0xFF054F31)),
  PxTag('lime', Color(0xFF1A2E05), Color(0xFFBEF264), Color(0xFF365314)),
  PxTag('yellow', Color(0xFF422006), Color(0xFFFDE047), Color(0xFF713F12)),
  PxTag('ochre', Color(0xFF451A03), Color(0xFFFCD34D), Color(0xFF78350F)),
  PxTag('clay', Color(0xFF331512), Color(0xFFDDA894), Color(0xFF5C2A20)),
];

/// Picks a stable swatch for a piece of text — a sender, a label, a tenant — so the
/// same name is always the same colour, without storing a colour per record.
PxTag pxTagFor(String seed, {required bool dark}) {
  final palette = dark ? pxTagDark : pxTagLight;
  var hash = 0;
  for (final unit in seed.codeUnits) {
    hash = (hash * 31 + unit) & 0x1fffffff;
  }
  // Skips index 0, the neutral swatch, which is reserved for 'no category'.
  return palette[1 + hash % (palette.length - 1)];
}
